linters:
  enable-all: true
  fast: false
  disable:
    - maligned
    - prealloc
    - wsl
    - nlreturn
    - wrapcheck
    - godox
    - golint
    - interfacer
    - scopelint
    - varnamelen
    - exhaustruct
    # Deprecated:
    - nosnakecase
    - deadcode
    - ifshort
    - structcheck
    - varcheck
    - exhaustivestruct

linters-settings:
  lll:
    line-length: 160

issues:
  exclude-rules:
    # Exclude some linters from tests
    - path: _test\.go
      linters:
        - funlen
        - lll
        - goconst
        - goerr113
        - dupl
        - paralleltest
        - gocognit
        - cyclop
        - forcetypeassert
        - ifshort
        - thelper
        - maintidx
