linters:
  enable-all: true
  fast: false
  disable:
    - prealloc
    - wsl
    - nlreturn
    - wrapcheck
    - godox
    - varnamelen
    - exhaustruct
    - ireturn
    - depguard
    # Deprecated:
    - execinquery
    - gomnd
    # We run staticcheck separately:
    - staticcheck
    - stylecheck

linters-settings:
  lll:
    line-length: 160

issues:
  exclude-rules:
    # Exclude some linters from tests
    - path: _test\.go
      linters:
        - funlen
        - lll
        - goconst
        - goerr113
        - dupl
        - paralleltest
        - gocognit
        - cyclop
        - forcetypeassert
        - ifshort
        - thelper
        - maintidx

    # Sometimes even unused parameter names can be helpful for documentation.
    # We can reconsider enabling this on a case by case basis in the future.
    - text: "unused-parameter: parameter '.*' seems to be unused"
      linters:
        - revive
