version: "2"

linters:
  default: all
  disable:
    - prealloc
    - wsl
    - wsl_v5
    - nlreturn
    - wrapcheck
    - godox
    - varnamelen
    - exhaustruct
    - ireturn
    - depguard
    - perfsprint
    - noinlineerr
    - embeddedstructfieldcheck
    # We run staticcheck separately:
    - staticcheck

  settings:
    lll:
      line-length: 160

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      - path: _test\.go
        linters:
          - funlen
          - lll
          - goconst
          - goerr113
          - dupl
          - paralleltest
          - gocognit
          - cyclop
          - forcetypeassert
          - ifshort
          - thelper
          - maintidx
          - inamedparam
          - err113
          - nilnil
          - mnd

      - text: singleCaseSwitch
        linters:
          - gocritic

      # Sometimes even unused parameter names can be helpful for documentation.
      # We can reconsider enabling this on a case by case basis in the future.
      - text: "unused-parameter: parameter '.*' seems to be unused"
        linters:
          - revive

formatters:
  enable:
    - gci
    - gofmt
    - goimports

  exclusions:
    generated: lax
