// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JosiahWitt/ensure/cmd/ensure/internal/fswrite (interfaces: FSWriteIface)

// Package mock_fswrite is a generated GoMock package.
package mock_fswrite

import (
	gomock "github.com/golang/mock/gomock"
	os "os"
	reflect "reflect"
)

// MockFSWriteIface is a mock of FSWriteIface interface
type MockFSWriteIface struct {
	ctrl     *gomock.Controller
	recorder *MockFSWriteIfaceMockRecorder
}

// MockFSWriteIfaceMockRecorder is the mock recorder for MockFSWriteIface
type MockFSWriteIfaceMockRecorder struct {
	mock *MockFSWriteIface
}

// NewMockFSWriteIface creates a new mock instance
func NewMockFSWriteIface(ctrl *gomock.Controller) *MockFSWriteIface {
	mock := &MockFSWriteIface{ctrl: ctrl}
	mock.recorder = &MockFSWriteIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFSWriteIface) EXPECT() *MockFSWriteIfaceMockRecorder {
	return m.recorder
}

// MkdirAll mocks base method
func (m *MockFSWriteIface) MkdirAll(arg0 string, arg1 os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll
func (mr *MockFSWriteIfaceMockRecorder) MkdirAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockFSWriteIface)(nil).MkdirAll), arg0, arg1)
}

// WriteFile mocks base method
func (m *MockFSWriteIface) WriteFile(arg0, arg1 string, arg2 os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile
func (mr *MockFSWriteIfaceMockRecorder) WriteFile(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockFSWriteIface)(nil).WriteFile), arg0, arg1, arg2)
}

// NEW creates a MockFSWriteIface.
func (*MockFSWriteIface) NEW(ctrl *gomock.Controller) *MockFSWriteIface {
	return NewMockFSWriteIface(ctrl)
}
