linters:
  enable-all: true
  fast: false
  disable:
    - prealloc
    - wsl
    - nlreturn
    - wrapcheck
    - godox
    - varnamelen
    - gofumpt
    - exhaustruct
    - ireturn
    - depguard
    # Deprecated:
    - execinquery
    - exportloopref
    - gomnd
    # We run staticcheck separately:
    - staticcheck
    - stylecheck

linters-settings:
  lll:
    line-length: 160

issues:
  exclude-rules:
    # Exclude some linters from tests
    - path: _test\.go
      linters:
        - funlen
        - lll
        - goconst
        - goerr113
        - dupl
        - paralleltest
        - gocognit
        - cyclop
        - forcetypeassert
        - ifshort
        - thelper
        - maintidx
        - inamedparam
        - err113
        - nilnil
        - mnd

    - text: singleCaseSwitch
      linters:
        - gocritic

    # Exclude some linters from fixtures and scenarios
    - path: .*(/fixtures/)|(/scenarios/).*
      linters:
        - gochecknoglobals

    - path: .*(/fixtures/)|(/scenarios/).*
      text: "underscores? in package name"
      linters:
        - revive
        - stylecheck

    - path: .*(/fixtures/)|(/scenarios/).*
      linters:
        - inamedparam

    - path: /mock.*/
      linters:
        - mnd

    # Sometimes even unused parameter names can be helpful for documentation.
    # We can reconsider enabling this on a case by case basis in the future.
    - text: "unused-parameter: parameter '.*' seems to be unused"
      linters:
        - revive
