// Code generated by `ensure mocks generate`. DO NOT EDIT.
// Source: github.com/JosiahWitt/ensure/cmd/ensure/internal/mockgen (interfaces: Generator)

// Package mock_mockgen is a generated GoMock package.
package mock_mockgen

import (
	"github.com/JosiahWitt/ensure/cmd/ensure/internal/ensurefile"
	"github.com/JosiahWitt/ensure/cmd/ensure/internal/ifacereader"
	"github.com/JosiahWitt/ensure/cmd/ensure/internal/mockgen"
	"github.com/JosiahWitt/ensure/cmd/ensure/internal/uniqpkg"
	"github.com/kr/pretty"
	"go.uber.org/mock/gomock"
	"reflect"
)

// MockGenerator is a mock of the Generator interface in github.com/JosiahWitt/ensure/cmd/ensure/internal/mockgen.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// NEW creates a MockGenerator. This method is used internally by ensure.
func (*MockGenerator) NEW(ctrl *gomock.Controller) *MockGenerator {
	return NewMockGenerator(ctrl)
}

// EXPECT returns a struct that allows setting up expectations.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// GenerateMocks mocks GenerateMocks on Generator.
func (m *MockGenerator) GenerateMocks(_pkgs []*ifacereader.Package, _imports *uniqpkg.UniquePackagePaths, _config *ensurefile.MockConfig) ([]*mockgen.PackageMock, error) {
	m.ctrl.T.Helper()
	inputs := []interface{}{_pkgs, _imports, _config}
	ret := m.ctrl.Call(m, "GenerateMocks", inputs...)
	ret0, _ := ret[0].([]*mockgen.PackageMock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateMocks sets up expectations for calls to GenerateMocks.
// Calling this method multiple times allows expecting multiple calls to GenerateMocks with a variety of parameters.
//
// Inputs:
//
//	pkgs []*ifacereader.Package
//	imports *uniqpkg.UniquePackagePaths
//	config *ensurefile.MockConfig
//
// Outputs:
//
//	[]*mockgen.PackageMock
//	error
func (mr *MockGeneratorMockRecorder) GenerateMocks(_pkgs interface{}, _imports interface{}, _config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	inputs := []interface{}{wrapMatcher(_pkgs), wrapMatcher(_imports), wrapMatcher(_config)}
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMocks", reflect.TypeOf((*MockGenerator)(nil).GenerateMocks), inputs...)
}

func wrapMatcher(input interface{}) gomock.Matcher {
	if matcher, ok := input.(gomock.Matcher); ok {
		return matcher
	}

	var assertionMatcher gomock.Matcher
	if input == nil {
		assertionMatcher = gomock.Nil()
	} else {
		assertionMatcher = gomock.Eq(input)
	}

	matcher := gomock.WantFormatter(
		gomock.StringerFunc(func() string {
			return pretty.Sprint(input)
		}),
		assertionMatcher,
	)

	return gomock.GotFormatterAdapter(
		gomock.GotFormatterFunc(func(got interface{}) string {
			return pretty.Sprint(got)
		}),
		matcher,
	)
}
