name: CI
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14, 1.15]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          go install github.com/golang/mock/mockgen@v1.4.4

      - name: Generate mocks
        run: make generate-mocks

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      # - name: Upload to codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}


  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14, 1.15]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.34.1

      - name: Lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run
