name: Docs
on: [push]
jobs:

  toc:
    name: Table of Contents
    runs-on: ubuntu-latest
    steps:

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Check out code
      uses: actions/checkout@v1

    - name: Install doctoc
      run: npm install -g doctoc@2.0

    - name: Verify doctoc was run
      run: |
        doctoc README.md
        if [[ $(git status --porcelain | grep README.md 2> /dev/null) ]]; then
          echo "❌ Please run doctoc (https://github.com/thlorenz/doctoc) after changing the README";
          exit 1;
        else
          echo "✅ doctoc was run";
        fi
